name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: main

env:
  GO_VERSION: '1.22.1'

permissions: read-all
jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Install gocover-cobertura
        run: |
          go get github.com/boumenot/gocover-cobertura && go install github.com/boumenot/gocover-cobertura
      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2            
      - name: Run tests
        run: go test -race -json -v -coverprofile=coverage.txt ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Convert go coverage to corbetura format
        run: gocover-cobertura < coverage.txt > coverage.xml
      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: false
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '86 100'

  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run tests
        run: make test-python
