name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Test with the Go CLI
        run: go test ./test/